<a href="https://colab.research.google.com/github/Aditya9790/Aditya/blob/master/ML_Modules.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
a = np.array([[1,2,10,44,10], [1,2,3,4,5]])
print(np.ndim(a)) # dimention of array
print(np.shape(a)) # size of array in the form of (m, n)

2
(2, 5)


In [ ]:
b = np.arange(1, 100, 22)
print(b)

[ 1 23 45 67 89]


In [ ]:
one = np.ones((2,6))
print(one)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [ ]:
rand_num = np.random.rand(4,2) # uniformly distributed numbers
print(rand_num)# from [0,1)

[[0.17213513 0.94493106]
 [0.47463212 0.94916632]
 [0.14653539 0.98324286]
 [0.80896044 0.70428604]]


In [ ]:
rand_normal = np.random.randn(4,2) # normally distributed numbers
print(rand_normal)# from [0,1)

[[-0.6942774   0.96296211]
 [ 0.42311077 -0.77967676]
 [-0.09583216 -0.76084324]
 [-1.20915817 -0.06839847]]


In [ ]:
rand_int = np.random.randint(2, 100, 12).reshape(3,4) # generated 10 random integers
print(rand_int)# from 2, 100
print(f'Dimention of rand_int is : {rand_int.ndim}')

[[72 37 35 58]
 [93 56 40  7]
 [ 2 46 22 20]]
Dimention of rand_int is : 2


In [ ]:
rand_int[0,1:]

array([37, 35, 58])

# **Pandas**

In [ ]:
arr = np.random.randint(-10, 10, 20).reshape(4, 5) # random matrix of (4, 5) size

In [ ]:
# create a data frame
df = pd.DataFrame(arr, index = 'A B C D'.split(), columns = 'V W X Y Z'.split())
print(df)

   V  W  X  Y  Z
A -4 -5  1  7 -7
B  9  8 -3  1 -4
C -6  6 -6 -8  1
D  4  2 -6 -6 -6


Generally we access the data frame by column names and not by row names

In [ ]:
df['W']

A   -5
B    8
C    6
D    2
Name: W, dtype: int64

To access two columns at the same time pass the column names as a list.

**NOTE :** 
Order is not important we can pass columns in any order as we like.

In [ ]:
df[['W', 'X', 'Y']]

W  X  Y
A -5  1  7
B  8 -3  1
C  6 -6 -8
D  2 -6 -6

To access the rows we use **loc** function, in loc we pass the row names.

We can access columns by **iloc** function, here we pass column index as a parameter

In [ ]:
df.loc[['A', 'B']]

V  W  X  Y  Z
A -4 -5  1  7 -7
B  9  8 -3  1 -4

In [ ]:
df.iloc[[0, 1], [0, 2]]

V  X
A -4  1
B  9 -3

In [ ]:
df.loc[['A'], ['V', 'W']]

V  W
A -4 -5

In [ ]:
df

V  W  X  Y  Z
A -4 -5  1  7 -7
B  9  8 -3  1 -4
C -6  6 -6 -8  1
D  4  2 -6 -6 -6

In [ ]:
df['W']<0

A     True
B    False
C    False
D    False
Name: W, dtype: bool

In [ ]:
df[df['W']<0]

V  W  X  Y  Z
A -4 -5  1  7 -7

In [ ]:
# Create a data frame
Employee = {'Sr No':[1,2,3,4,5], 'Name':['Aditya', 'Michel', 'Mark', 'Abby', 'Lara'], 'Monthly Salary':[90000, 100000, 80000, 76000, 87000]}
Table = pd.DataFrame(Employee)
print(Table)

   Sr No    Name  Monthly Salary
0      1  Aditya           90000
1      2  Michel          100000
2      3    Mark           80000
3      4    Abby           76000
4      5    Lara           87000


# **Import file from google drive**

In [ ]:
from google.colab import files
uploaded = files.upload('/content/IPL IMB381IPL2013.csv')

TypeError: ignored

In [ ]:
import io
ipl_data = pd.read_csv(io.BytesIO(uploaded['IPL IMB381IPL2013.csv']))
print(ipl_data.head(5))

KeyError: ignored